[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mmcifreader"
authors = [{name = "Morten Kjeldgaard", email = "mortenkjeldgaard@gmail.com"}]
description = "Python module to parse mmCIF file"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "BSD-3-Clause"}
dynamic = ["version"]

[tool.setuptools]
packages =  ["mmciflexer", "mmcifreader"]

[tool.setuptools.dynamic]
version = {attr = "mmcifreader.__version__"}
