[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mmcifreader"
authors = [{name = "Morten Kjeldgaard", email = "mortenkjeldgaard@gmail.com"}]
description = "Python module to parse mmCIF file"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "BSD-3-Clause"}
classifiers = [
    "Programming Language :: Python :: 3",
]
dynamic = ["version"]
dependencies = ["logguru"]

[tool.setuptools]
packages =  ["mmcifreader", "mmcifreader.mmciflexer"]

[tool.setuptools.dynamic]
version = {attr = "mmcifreader.__version__"}
