[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mmcifreader"
authors = [{name = "Morten Kjeldgaard", email = "mortenkjeldgaard@gmail.com"}]
description = "Python module to parse mmCIF file"
readme = "README.md"
requires-python = ">=3.10"
license = {file="LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: C",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Topic :: File Formats",
    "Topic :: Scientific/Engineering :: Interface Engine/Protocol Translator"
]
dynamic = ["version"]
dependencies = ["loguru"]

[tool.setuptools]
packages =  ["mmcifreader", "mmcifreader.mmciflexer"]

[tool.setuptools.dynamic]
version = {attr = "mmcifreader.__version__"}
