[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mmciflex"
version="0.2.2"
authors = [
    {name = "Morten Kjeldgaard", email = "mortenkjeldgaard@gmail.com"},
]
description = "Python module to parse mmCIF file"
#readme = "README.rst"
requires-python = ">=3.7"
license = {text = "BSD-3-Clause"}

[tool.setuptools]
py-modules = []
